// Auto-generated by vite-plugin-page-registry.ts — DO NOT EDIT
import type { ComponentPageMeta } from '../framework/types'

export interface PageEntry extends ComponentPageMeta {
  slug: string
}

export interface CategoryEntry {
  name: string
  icon: string
  pages: PageEntry[]
}

export const pages: PageEntry[] = [
  {
    "name": "Accordion",
    "category": "Layout",
    "component": "Accordion",
    "description": "Expandable content sections with single or multiple open item support.",
    "icon": "lucide:chevrons-down",
    "order": 1,
    "slug": "accordion"
  },
  {
    "name": "Badge",
    "category": "Data Display",
    "component": "Badge",
    "description": "Small label for status indicators, counts, or categories.",
    "icon": "lucide:tag",
    "order": 2,
    "slug": "badge"
  },
  {
    "name": "Button",
    "category": "Form Inputs",
    "component": "Button",
    "description": "A clickable button with multiple variants, sizes, colors, and states.",
    "icon": "lucide:mouse-pointer",
    "order": 1,
    "slug": "button"
  },
  {
    "name": "Divider",
    "category": "Layout",
    "component": "Divider",
    "description": "A visual separator between content sections.",
    "icon": "lucide:minus",
    "order": 3,
    "slug": "divider"
  },
  {
    "name": "Drawer",
    "category": "Overlays",
    "component": "Drawer",
    "description": "A sliding panel anchored to any edge of the viewport.",
    "icon": "lucide:panel-right",
    "order": 2,
    "slug": "drawer"
  },
  {
    "name": "Modal",
    "category": "Overlays",
    "component": "Modal",
    "description": "A dialog overlay for focused interactions, with customizable size and position.",
    "icon": "lucide:square",
    "order": 1,
    "slug": "modal"
  },
  {
    "name": "ProgressBar",
    "category": "Data Display",
    "component": "ProgressBar",
    "description": "A horizontal bar indicating progress or loading state.",
    "icon": "lucide:loader",
    "order": 3,
    "slug": "progress-bar"
  },
  {
    "name": "Skeleton",
    "category": "Data Display",
    "component": "Skeleton",
    "description": "Placeholder loading indicators for content that is still loading.",
    "icon": "lucide:layout",
    "order": 4,
    "slug": "skeleton"
  },
  {
    "name": "Switch",
    "category": "Form Inputs",
    "component": "Switch",
    "description": "A toggle switch for boolean on/off states.",
    "icon": "lucide:toggle-left",
    "order": 5,
    "slug": "switch"
  },
  {
    "name": "Tabs",
    "category": "Navigation",
    "component": "Tabs",
    "description": "Tabbed navigation for switching between content panels.",
    "icon": "lucide:layout-list",
    "order": 2,
    "slug": "tabs"
  },
  {
    "name": "Tooltip",
    "category": "Overlays",
    "component": "Tooltip",
    "description": "A small popup that shows contextual information on hover or focus.",
    "icon": "lucide:message-square",
    "order": 3,
    "slug": "tooltip"
  }
]

export const categories: CategoryEntry[] = [
  {
    "name": "Layout",
    "icon": "lucide:layout",
    "pages": [
      {
        "name": "Accordion",
        "category": "Layout",
        "component": "Accordion",
        "description": "Expandable content sections with single or multiple open item support.",
        "icon": "lucide:chevrons-down",
        "order": 1,
        "slug": "accordion"
      },
      {
        "name": "Divider",
        "category": "Layout",
        "component": "Divider",
        "description": "A visual separator between content sections.",
        "icon": "lucide:minus",
        "order": 3,
        "slug": "divider"
      }
    ]
  },
  {
    "name": "Data Display",
    "icon": "lucide:bar-chart-3",
    "pages": [
      {
        "name": "Badge",
        "category": "Data Display",
        "component": "Badge",
        "description": "Small label for status indicators, counts, or categories.",
        "icon": "lucide:tag",
        "order": 2,
        "slug": "badge"
      },
      {
        "name": "ProgressBar",
        "category": "Data Display",
        "component": "ProgressBar",
        "description": "A horizontal bar indicating progress or loading state.",
        "icon": "lucide:loader",
        "order": 3,
        "slug": "progress-bar"
      },
      {
        "name": "Skeleton",
        "category": "Data Display",
        "component": "Skeleton",
        "description": "Placeholder loading indicators for content that is still loading.",
        "icon": "lucide:layout",
        "order": 4,
        "slug": "skeleton"
      }
    ]
  },
  {
    "name": "Form Inputs",
    "icon": "lucide:text-cursor-input",
    "pages": [
      {
        "name": "Button",
        "category": "Form Inputs",
        "component": "Button",
        "description": "A clickable button with multiple variants, sizes, colors, and states.",
        "icon": "lucide:mouse-pointer",
        "order": 1,
        "slug": "button"
      },
      {
        "name": "Switch",
        "category": "Form Inputs",
        "component": "Switch",
        "description": "A toggle switch for boolean on/off states.",
        "icon": "lucide:toggle-left",
        "order": 5,
        "slug": "switch"
      }
    ]
  },
  {
    "name": "Overlays",
    "icon": "lucide:layers",
    "pages": [
      {
        "name": "Modal",
        "category": "Overlays",
        "component": "Modal",
        "description": "A dialog overlay for focused interactions, with customizable size and position.",
        "icon": "lucide:square",
        "order": 1,
        "slug": "modal"
      },
      {
        "name": "Drawer",
        "category": "Overlays",
        "component": "Drawer",
        "description": "A sliding panel anchored to any edge of the viewport.",
        "icon": "lucide:panel-right",
        "order": 2,
        "slug": "drawer"
      },
      {
        "name": "Tooltip",
        "category": "Overlays",
        "component": "Tooltip",
        "description": "A small popup that shows contextual information on hover or focus.",
        "icon": "lucide:message-square",
        "order": 3,
        "slug": "tooltip"
      }
    ]
  },
  {
    "name": "Navigation",
    "icon": "lucide:compass",
    "pages": [
      {
        "name": "Tabs",
        "category": "Navigation",
        "component": "Tabs",
        "description": "Tabbed navigation for switching between content panels.",
        "icon": "lucide:layout-list",
        "order": 2,
        "slug": "tabs"
      }
    ]
  }
]
