// Auto-generated by vite-plugin-page-registry.ts — DO NOT EDIT
import type { ComponentPageMeta } from '../framework/types'

export interface PageEntry extends ComponentPageMeta {
  slug: string
}

export interface CategoryEntry {
  name: string
  icon: string
  pages: PageEntry[]
}

export const pages: PageEntry[] = [
  {
    "name": "Accordion",
    "category": "Layout",
    "component": "Accordion",
    "description": "Expandable content sections with single or multiple open item support.",
    "icon": "lucide:chevrons-down",
    "order": 1,
    "slug": "accordion"
  },
  {
    "name": "Badge",
    "category": "Data Display",
    "component": "Badge",
    "description": "Small label for status indicators, counts, or categories.",
    "icon": "lucide:tag",
    "order": 2,
    "slug": "badge"
  },
  {
    "name": "Button",
    "category": "Form Inputs",
    "component": "Button",
    "description": "A clickable button with multiple variants, sizes, colors, and states.",
    "icon": "lucide:mouse-pointer",
    "order": 1,
    "slug": "button"
  },
  {
    "name": "Modal",
    "category": "Overlays",
    "component": "Modal",
    "description": "A dialog overlay for focused interactions, with customizable size and position.",
    "icon": "lucide:square",
    "order": 1,
    "slug": "modal"
  }
]

export const categories: CategoryEntry[] = [
  {
    "name": "Layout",
    "icon": "lucide:layout",
    "pages": [
      {
        "name": "Accordion",
        "category": "Layout",
        "component": "Accordion",
        "description": "Expandable content sections with single or multiple open item support.",
        "icon": "lucide:chevrons-down",
        "order": 1,
        "slug": "accordion"
      }
    ]
  },
  {
    "name": "Data Display",
    "icon": "lucide:bar-chart-3",
    "pages": [
      {
        "name": "Badge",
        "category": "Data Display",
        "component": "Badge",
        "description": "Small label for status indicators, counts, or categories.",
        "icon": "lucide:tag",
        "order": 2,
        "slug": "badge"
      }
    ]
  },
  {
    "name": "Form Inputs",
    "icon": "lucide:text-cursor-input",
    "pages": [
      {
        "name": "Button",
        "category": "Form Inputs",
        "component": "Button",
        "description": "A clickable button with multiple variants, sizes, colors, and states.",
        "icon": "lucide:mouse-pointer",
        "order": 1,
        "slug": "button"
      }
    ]
  },
  {
    "name": "Overlays",
    "icon": "lucide:layers",
    "pages": [
      {
        "name": "Modal",
        "category": "Overlays",
        "component": "Modal",
        "description": "A dialog overlay for focused interactions, with customizable size and position.",
        "icon": "lucide:square",
        "order": 1,
        "slug": "modal"
      }
    ]
  }
]
