import type { Plugin } from 'vite'
import * as path from 'path'
import * as fs from 'fs'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const PAGES_DIR = path.resolve(__dirname, '../src/pages/components')
const REGISTRY_DIR = path.resolve(__dirname, '../src/registry')
const OUTPUT_FILE = path.join(REGISTRY_DIR, 'page-registry.ts')

/** Category icons for sidebar groups */
const CATEGORY_ICONS: Record<string, string> = {
  Buttons: 'lucide:mouse-pointer-click',
  'Text Inputs': 'lucide:text-cursor-input',
  Selection: 'lucide:check-square',
  Pickers: 'lucide:list-filter',
  Navigation: 'lucide:compass',
  Layout: 'lucide:layout-grid',
  Overlays: 'lucide:layers',
  'Data Display': 'lucide:eye',
  'Tables & Media': 'lucide:table',
  Feedback: 'lucide:message-circle',
  'Form Inputs': 'lucide:clipboard-edit',
  Media: 'lucide:play',
  'Rich Editors': 'lucide:pen-line',
  'Schema Forms': 'lucide:braces',
  Authentication: 'lucide:shield',
  Utilities: 'lucide:wrench',
}

interface PageMeta {
  name: string
  category: string
  description: string
  component: string
  icon?: string
  order?: number
  tags?: string[]
}

function extractMetaFromFile(filePath: string): PageMeta | null {
  const content = fs.readFileSync(filePath, 'utf-8')

  // Extract the meta export object literal
  const metaMatch = content.match(
    /export\s+const\s+meta\s*(?::\s*\w+)?\s*=\s*(\{[\s\S]*?\n\})/
  )
  if (!metaMatch) return null

  try {
    const objStr = metaMatch[1]
      .replace(/\/\/.*$/gm, '') // Remove single-line comments
      .replace(/,\s*\}/g, '}') // Remove trailing commas

    const fn = new Function(`return ${objStr}`)
    return fn() as PageMeta
  } catch {
    console.warn(`[page-registry] Could not parse meta from ${filePath}`)
    return null
  }
}

function generate() {
  if (!fs.existsSync(REGISTRY_DIR)) {
    fs.mkdirSync(REGISTRY_DIR, { recursive: true })
  }

  if (!fs.existsSync(PAGES_DIR)) {
    fs.writeFileSync(
      OUTPUT_FILE,
      [
        '// Auto-generated by vite-plugin-page-registry.ts — DO NOT EDIT',
        "import type { ComponentPageMeta } from '../framework/types'",
        '',
        'export interface PageEntry extends ComponentPageMeta {',
        '  slug: string',
        '}',
        '',
        'export interface CategoryEntry {',
        '  name: string',
        '  icon: string',
        '  pages: PageEntry[]',
        '}',
        '',
        'export const pages: PageEntry[] = []',
        'export const categories: CategoryEntry[] = []',
        '',
      ].join('\n'),
      'utf-8'
    )
    return
  }

  const files = fs
    .readdirSync(PAGES_DIR)
    .filter(f => f.endsWith('.ts') && !f.startsWith('_'))
    .sort()

  const pages: Array<PageMeta & { slug: string }> = []

  for (const file of files) {
    const filePath = path.join(PAGES_DIR, file)
    const slug = file.replace(/\.ts$/, '')
    const meta = extractMetaFromFile(filePath)

    if (meta) {
      pages.push({ ...meta, slug })
    } else {
      console.warn(`[page-registry] Skipping ${file} — no meta export found`)
    }
  }

  // Group by category
  const categoryMap = new Map<string, typeof pages>()
  for (const page of pages) {
    const group = categoryMap.get(page.category) ?? []
    group.push(page)
    categoryMap.set(page.category, group)
  }

  // Sort pages within each category by order, then name
  for (const group of categoryMap.values()) {
    group.sort(
      (a, b) => (a.order ?? 999) - (b.order ?? 999) || a.name.localeCompare(b.name)
    )
  }

  const categories = Array.from(categoryMap.entries()).map(
    ([name, catPages]) => ({
      name,
      icon: CATEGORY_ICONS[name] ?? 'lucide:component',
      pages: catPages,
    })
  )

  const source = [
    '// Auto-generated by vite-plugin-page-registry.ts — DO NOT EDIT',
    "import type { ComponentPageMeta } from '../framework/types'",
    '',
    'export interface PageEntry extends ComponentPageMeta {',
    '  slug: string',
    '}',
    '',
    'export interface CategoryEntry {',
    '  name: string',
    '  icon: string',
    '  pages: PageEntry[]',
    '}',
    '',
    `export const pages: PageEntry[] = ${JSON.stringify(pages, null, 2)}`,
    '',
    `export const categories: CategoryEntry[] = ${JSON.stringify(categories, null, 2)}`,
    '',
  ].join('\n')

  fs.writeFileSync(OUTPUT_FILE, source, 'utf-8')
  console.log(
    `[page-registry] Registered ${pages.length} pages in ${categoryMap.size} categories`
  )
}

export function pageRegistryPlugin(): Plugin {
  return {
    name: 'beatui-page-registry',
    buildStart() {
      generate()
    },
    configureServer(server) {
      server.watcher.add(PAGES_DIR + '/**/*.ts')
      server.watcher.on('change', (file: string) => {
        if (file.startsWith(PAGES_DIR) && file.endsWith('.ts')) {
          console.log('[page-registry] Page changed, regenerating...')
          try {
            generate()
          } catch (e) {
            console.error('[page-registry] Error regenerating:', e)
          }
        }
      })
    },
  }
}
